server:
  port: 9002
  servlet:
    context-path: /api

spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:mysql://localhost:3306/attendance-service
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    discovery:
      enabled: true
  kafka:
    bootstrap-servers: 9092
    template:
      default-topic: attendanceResult
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.ali.attendanceservice.event.SwipeTotalHoursEvent


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8089/eureka


