server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8089/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionLocator: INFO

spring:
  application:
    name:  api-gateway
  cloud:
    gateway:
      routes:
        - id: discovery-service
          uri: lb://DISCOVERY-SERVICE
          predicates: Path=/eureka/web
          filters: SetPath=/

        - id: attendance-service
          uri: lb://ATTENDANCE-SERVICE
          predicates: Path=/api/attendance/**

        - id: swipe-service
          uri: lb://SWIPE-SERVICE
          predicates: Path=/api/swipe/**

        - id: discovery-server-static-resource
          uri: http://localhost:8088
          predicates: Path=/eureka/**
      discovery:
        locator:
          enabled: true

management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
    web:
      exposure:
        include: health, gateway, info, env