server:
  port: 9001
  servlet:
    context-path: /api

spring:
  application:
    name: swipe-service
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: swipe-service
      uri: mongodb://localhost:27017/swipe-service
  cloud:
    discovery:
      enabled: true
  kafka:
    bootstrap-servers: 9092
    template:
      default-topic: attendanceResult
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.ali.swipeservice.event.SwipeTotalHoursEvent


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8089/eureka