server:
  port: 8088

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}

spring:
  application:
    name: discovery-service